QiyasPlatform/Qiyas.WebAdmin/Controllers/BookPackingOperationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;
using DevExpress.Web.Mvc;
using Qiyas.BusinessLogicLayer;
using System.Security.Cryptography;
using System.Text;
using System.IO;
namespace Qiyas.WebAdmin.Controllers
{
    [Authorize]
    public class BookPackingOperationController : Controller
    {
        public int PrintingOperationID
        {
            set
            {
                var key = "34FAA431-CF79-4869-9488-93F6AAE81263";
                var Session = HttpContext.Session;
                Session[key] = value;
            }
            get
            {
                var key = "34FAA431-CF79-4869-9488-93F6AAE81263";
                var Session = HttpContext.Session;
                if (Session[key] == null)
                    Session[key] = 0;
                return (int)Session[key];
            }
        }

        public ActionResult Index(int ID = 0)
        {
            string url = string.Format("{0}", Url.Action("Index", "BookPrintingOperation"));
            var model = new BusinessLogicLayer.Entity.PPM.BookPrintingOperation(ID);
            if (model == null || !model.HasObject)
            {
                return RedirectToAction("Index", "BookPrintingOperation");
            }
            MainID = ID;
            ViewBag.HasError = false;
            ViewBag.NotifyMessage = "";
            ViewBag.PrintingID = ID;
            ViewBag.IsSaved = model.OperationStatusID > 1;
            PrintingOperationID = ID;
            return View(model);

        }

        public ActionResult PrintPacks(int ID = 0)
        {
            string url = string.Format("{0}", Url.Action("Index", "BookPrintingOperation"));
            var model = new BusinessLogicLayer.Entity.PPM.BookPrintingOperation(ID);
            if (model == null || !model.HasObject)
            {
                return RedirectToAction("Index", "BookPrintingOperation");
            }
            
            MainID = ID;
            ViewBag.HasError = false;
            ViewBag.NotifyMessage = "";
            ViewBag.PrintingID = ID;
            PrintingOperationID = ID;
            ViewBag.IsSaved = model.OperationStatusID > 1;

            report.DataSource = new Qiyas.BusinessLogicLayer.Components.PPM.BookPackItemLogic().GetAllByPrintingIDForPrinting(Qiyas.WebAdmin.Controllers.BookPackingOperationController.MainID);
            var stream = new MemoryStream();
            report.ExportToPdf(stream);
            return File(stream.GetBuffer(), "application/pdf");
            //return View(model);
        }

        #region Grid Operations
        [ValidateInput(false)]
        public ActionResult PackingGridViewPartial()
        {
            var model = new BusinessLogicLayer.Components.PPM.BookPackingOperationLogic().GetByBookPrintingID(PrintingOperationID);
            var modelPrinting = new BusinessLogicLayer.Entity.PPM.BookPrintingOperation(MainID);
            ViewBag.IsSaved = modelPrinting.OperationStatusID > 1;
            return PartialView("_PackingGridViewPartial", model);
        }

        [ValidateInput(false)]
        public ActionResult RePackingGridViewPartial()
        {
            var model = new BusinessLogicLayer.Components.PPM.ViewBookRepackOperationLogic().GetAll(PrintingOperationID);
            var modelPrinting = new BusinessLogicLayer.Entity.PPM.BookPrintingOperation(MainID);
            ViewBag.IsSaved = modelPrinting.OperationStatusID > 1;
            return PartialView("_RePackingGridViewPartial", model);
        }

        public int GetTotalPerBooks()
        {
            int totalBooksPerModel = 0;
            var model = new BusinessLogicLayer.Components.PPM.BookPackingOperationLogic().GetByBookPrintingID(PrintingOperationID);
            foreach (var item in model)
            {
                if (item.PackingCalculationTypeID == 2)
                    continue;
                var ptype = new BusinessLogicLayer.Entity.PPM.PackagingType(item.PackagingTypeID.Value);
                if (ptype.BooksPerPackage == 3 && ptype.ExamModelCount == 1)
                {
                    //totalA3 += item.PackageTotal.Value;
                }
                else
                {
                    if (item.NumberofBooksPerModel.HasValue)
                        totalBooksPerModel += item.NumberofBooksPerModel.Value;
                    
                }

            }
            return totalBooksPerModel;
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult PackingGridViewPartialAddNew([ModelBinder(typeof(DevExpressEditorsBinder))] Qiyas.BusinessLogicLayer.Entity.PPM.BookPackingOperation item)
        {
            
            if (ModelState.IsValid)
            {
                try
                {
                    bool isValid = true;
                    if(item.PackingCalculationTypeID == 2)
                    {
                        if (item.PackingParentID == null || item.PackingParentID == 0)
                        {
                            ViewData["EditError"] = Resources.MainResource.EnterPackingParentID;
                            isValid = false;
                            var models = new BusinessLogicLayer.Components.PPM.BookPackingOperationLogic().GetByBookPrintingID(PrintingOperationID);
                            var modelPrintings = new BusinessLogicLayer.Entity.PPM.BookPrintingOperation(MainID);
                            ViewBag.IsSaved = modelPrintings.OperationStatusID > 1;
                            return PartialView("_PackingGridViewPartial", models);
                        }
                    }
                    int totalPackage = TotalPackages(item);
                    if(totalPackage == 0)
                    {
                        ViewData["EditError"] = "يجب ان يكون العدد اكبر من صفر";
                        isValid = false;
                        var models = new BusinessLogicLayer.Components.PPM.BookPackingOperationLogic().GetByBookPrintingID(PrintingOperationID);
                        var modelPrintings = new BusinessLogicLayer.Entity.PPM.BookPrintingOperation(MainID);
                        ViewBag.IsSaved = modelPrintings.OperationStatusID > 1;
                        return PartialView("_PackingGridViewPartial", models);
                    }
                    BusinessLogicLayer.Entity.PPM.BookPrintingOperation printingOperation = new BusinessLogicLayer.Entity.PPM.BookPrintingOperation(PrintingOperationID);
                    var packType = new BusinessLogicLayer.Entity.PPM.PackagingType(item.PackagingTypeID.Value);
                    if(item.PackingCalculationTypeID == 3)
                    {
                        if ((item.PackingValue.Value % packType.BooksPerPackage.Value) != 0)
                        {
                            ViewData["EditError"] = Resources.MainResource.AllowDivisionForPackageValue;
                            isValid = false;
                        }
                        if(packType.ExamModelCount.Value == 1 && packType.BooksPerPackage.Value == 3)
                        {
                            if (item.PackingValue > printingOperation.ExamsNeededForA3)
                            {
                                ViewData["EditError"] = Resources.MainResource.EnterNumberLessThanBooksCount;
                                isValid = false;
                            }
                        }
                        else
                        {
                            if (item.PackingValue > printingOperation.PrintsForOneModel)
                            {
                                ViewData["EditError"] = Resources.MainResource.EnterNumberLessThanBooksCount;
                                isValid = false;
                            }
                        }
                        
                    }
                    int totalPerBook = GetTotalPerBooks();
                    if(item.NumberofBooksPerModel.HasValue)
                    {
                        if(item.PackingCalculationTypeID != 2)
                        {
                            totalPerBook += item.NumberofBooksPerModel.Value;
                            if (totalPerBook > printingOperation.PrintsForOneModel.Value)
                            {
                                ViewData["EditError"] = "العدد اكبر من المتاح";
                                isValid = false;
                                var models = new BusinessLogicLayer.Components.PPM.BookPackingOperationLogic().GetByBookPrintingID(PrintingOperationID);
                                var modelPrintings = new BusinessLogicLayer.Entity.PPM.BookPrintingOperation(MainID);
                                ViewBag.IsSaved = modelPrintings.OperationStatusID > 1;
                                return PartialView("_PackingGridViewPartial", models);
                            }
                        }
                        else
                        {
                            
                            int totalBooksPerModel = 0;
                            var modelSub = new BusinessLogicLayer.Components.PPM.BookPackingOperationLogic().GetByBookPrintingID(PrintingOperationID);
                            foreach (var itemSub in modelSub)
                            {
                                if (itemSub.PackingCalculationTypeID != 2 && itemSub.PackingParentID != item.PackingParentID)
                                    continue;

                                if (itemSub.NumberofBooksPerModel.HasValue)
                                    totalBooksPerModel += itemSub.NumberofBooksPerModel.Value;
                            }
                            BusinessLogicLayer.Entity.PPM.BookPackingOperation subOP = new BusinessLogicLayer.Entity.PPM.BookPackingOperation(item.PackingParentID.Value);
                            int totalForParent = subOP.NumberofBooksPerModel.Value;

QiyasPlatform/Qiyas.WebAdmin/Views/BookPackingOperation/Index.cshtml
@model Qiyas.BusinessLogicLayer.Entity.PPM.BookPrintingOperation

@{
    ViewBag.Title = @Resources.MainResource.BookPackingTitle;
}

<div class="page-title">
    <h1>
        @Resources.MainResource.BookPackingTitle
    </h1>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="widget-container fluid-height clearfix">
            <div class="widget-content padded clearfix">

                @using (Html.BeginForm("SavePackage", "BookPackingOperation", FormMethod.Post, new { @class = "form-horizontal", role = "form", @id = "packForm", @name = "packForm" }))
                {
                    @Html.AntiForgeryToken()

                    if (ViewBag.HasError)
                    {
                        <div class="alert alert-danger">@ViewBag.NotifyMessage</div>
                    }
                    else if (!string.IsNullOrEmpty(ViewBag.NotifyMessage))
                    {
                        <div class="alert alert-success">@ViewBag.NotifyMessage</div>
                    }
                    <div class="col-lg-4 pull-right">
                        @Html.ValidationSummary("", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(m => m.ExamCode, new { @class = "col-md-5  pull-right control-label" })
                            <div class="col-md-4  pull-right">
                                @Html.TextBoxFor(m => m.ExamCode, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.PrintsForOneModel, new { @class = "col-md-5  pull-right control-label" })
                            <div class="col-md-4 pull-right">
                                @Html.TextBoxFor(m => m.PrintsForOneModel, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.ExamsNeededForA3, new { @class = "col-md-5  pull-right control-label" })
                            <div class="col-md-4 pull-right">
                                @Html.TextBoxFor(m => m.ExamsNeededForA3, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.ExamsNeededForCD, new { @class = "col-md-5  pull-right control-label" })
                            <div class="col-md-4 pull-right">
                                @Html.TextBoxFor(m => m.ExamsNeededForCD, new { @class = "form-control" })
                            </div>
                        </div>
                        <hr />
                    </div>
                    <br /><br />
                    @Html.Action("PackingGridViewPartial")
                    <br /><br />
                    <h2>المعاد تحزيمه</h2>
    <br /><br />
                    @Html.Action("RePackingGridViewPartial")
    <br /><br />
                    <div class="pull-left">
                        <table>
                            <tr>
                                <td style="margin-left:10px;margin-bottom:10px;">
                                    اجمالي عدد الحزم
                                </td>
                                <td style="margin-left:10px;margin-bottom:10px;">
                                    <input id="bpoTotalPackage" type="text" readonly="readonly" value="0" />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                   اجمالي عدد الحزم للنموذج
                                </td>
                                <td>
                                    <input id="bpoTotalPackagePerModel" type="text" readonly="readonly" value="0" />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    اجمالي كمية الكتب للنموذج
                                </td>
                                <td>
                                    <input id="bpoTotalPackageBooksPerModel" type="text" readonly="readonly" value="0" />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    المتبقي من كمية الكتب للنموذج
                                </td>
                                <td>
                                    <input id="bpoRemainingPerModel" type="text" readonly="readonly" value="0" />
                                </td>
                            </tr>
                        </table>

                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            @if (ViewBag.IsSaved)
                            {
                            <input type="submit" name="PrintPacks" id="PrintPacks" value="طباعة ملصقات" class="btn btn-default btn-primary" />
                            }
                            else
                            {
                            <input type="submit" name="NumberingPacks" id="NumberingPacks" value="ترقيم الحزم" class="btn btn-default btn-primary" />
                            }

                            @*<input type="submit" name="SavePack" id="SavePack" value="حفظ" class="btn btn-default btn-primary" />*@



                            <input type="submit" name="DeletePack" id="DeletePack" value="حذف" class="btn btn-default btn-primary" />
                            <input type="button" name="BackButton" id="BackButton" value="عودة" class="btn btn-default " />
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</div>



@section Scripts {
    <script type="text/javascript">
    var url = "@Url.Action("GetPackingTotals", "BookPackingOperation")";
    GetPackingTotals(url);

    

    function GetPackingTotals(urlLink) {


        $.ajax({
            type: "POST",
            dataType: "json",
            data:  {
                item: 0
            },
            url: urlLink,
            success: function (data) {

                $('#bpoTotalPackage').val(data.Total);
                $('#bpoTotalPackagePerModel').val(data.TotalPerModel);
                $('#bpoTotalPackageBooksPerModel').val(data.TotalBooksPerModel);
                $('#bpoRemainingPerModel').val(data.RemainingPerModel);
                //totalObject.Total = totalCount;
                //totalObject.TotalA3 = totalA3;
                //totalObject.TotalBooksPerModel = totalBooksPerModel;
                //totalObject.TotalPerModel = totalPerModel;
            },
            error: function (data) {
                alert("e" + data);
                //$('#packageExists').hide();
                //$('#packageDoesntExist').show();
            }
        });

    }
    $("#SavePack").click(function (e) {
        var r = confirm("هل تريد حفظ التحزيم");
        if (r == true) {
            var form = $("form#packForm");
            form.attr("action", "@Url.Action("SavePack", "BookPackingOperation")");
            form.submit();
        } else {
            e.preventDefault();
            return false;
            //e.cancel = true;

        }

    });

    $("#DeletePack").click(function (e) {
        var r = confirm("هل تريد حذف هذا التحزيم");
        if (r == true) {
            var form = $("form#packForm");
            form.attr("action", "@Url.Action("DeletePack", "BookPackingOperation")");
            form.submit();
        } else {
            e.preventDefault();
            return false;
        }

    });

    $("#NumberingPacks").click(function (e) {
        var r = confirm("هل تريد إتمام الترقيم");
        if (r == true) {
            var form = $("form#packForm");
            form.attr("action", "@Url.Action("NumberingPack", "BookPackingOperation")");
                form.submit();
            } else {
                e.preventDefault();
                return false;
            }

        });

        $("#PrintPacks").click(function (e) {
            e.preventDefault();
            var urlMain = "@Url.Action("PrintPacks", "BookPackingOperation")";
            var url = urlMain + "/" + @Qiyas.WebAdmin.Controllers.BookPackingOperationController.MainID;
            window.open(url,"_blank");
        //window.location = "/BookPackingOperation/PrintPacks/" + @Qiyas.WebAdmin.Controllers.BookPackingOperationController.MainID;
        return false;
        @*var form = $("form#packForm");
            form.attr("action", "@Url.Action("PrinPacks", "BookPackingOperation", Qiyas.WebAdmin.Controllers.BookPackingOperationController.MainID)");
            form.submit();*@
    });

    $("#BackButton").click(function (e) {
        e.preventDefault();
        window.location = "/BookPrintingOperation";
        return false;
        @*var form = $("form#packForm");
            form.attr("action", "@Url.Action("PrinPacks", "BookPackingOperation", Qiyas.WebAdmin.Controllers.BookPackingOperationController.MainID)");
            form.submit();*@
    });
    </script>
}

QiyasPlatform/Qiyas.WebAdmin/Views/BookPackingOperation/PrintPacks.cshtml
@model Qiyas.BusinessLogicLayer.Entity.PPM.BookPrintingOperation

@{
    ViewBag.Title = @Resources.MainResource.PrintPacksTitle;
}

<div class="page-title">
    <h1>
        @Resources.MainResource.PrintPacksTitle
    </h1>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="widget-container fluid-height clearfix">
            <div class="widget-content padded clearfix">
                @Html.Action("PrintPacksTitleDocumentViewerPartial")
                <br />
                <br />
                <form>
                    <input type="button" name="BackButton" id="BackButton" value="عودة" class="btn btn-default " />
                </form>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script type="text/javascript">
    $("#BackButton").click(function (e) {
        e.preventDefault();
        var url = "@Url.Action("Index", "BookPackingOperation")" + "/Index/" + "@Model.BookPrintingOperationID";
        window.location = url ;
        return false;

    });
</script>
}

QiyasPlatform/Qiyas.WebAdmin/Views/BookPackingOperation/_PrintPacksTitleDocumentViewerPartial.cshtml
@Html.DevExpress().DocumentViewer(settings => {
    settings.Name = "PrintPacksDocumentViewer";
    settings.CallbackRouteValues = new { Controller = "BookPackingOperation", Action = "PrintPacksTitleDocumentViewerPartial" };
    settings.ExportRouteValues = new { Controller = "BookPackingOperation", Action = "PrintPacksTitleDocumentViewerPartialExport" };
    settings.SettingsReportViewer.PageByPage = true;
    
	settings.Report = (XtraReport)Model;
    settings.Width = 680;
    settings.Report.DataSource = new Qiyas.BusinessLogicLayer.Components.PPM.BookPackItemLogic().GetAllByPrintingIDForPrinting(Qiyas.WebAdmin.Controllers.BookPackingOperationController.MainID);
	settings.ToolbarMode = DocumentViewerToolbarMode.StandardToolbar;
}).GetHtml()

QiyasPlatform/Qiyas.WebAdmin/Views/BookPackingOperation/_RePackingGridViewPartial.cshtml
@using Qiyas.WebAdmin.Common.Helpers

@{
	var grid = Html.DevExpress().GridView(settings => {
        settings.Name = "gridRePack";
        settings.CallbackRouteValues = new { Controller = "BookPackingOperation", Action = "RePackingGridViewPartial" };

        
        


        settings.SettingsBehavior.ConfirmDelete = true;
        settings.SettingsEditing.Mode = GridViewEditingMode.Inline;

        settings.CommandColumn.ShowNewButtonInHeader = false;
        settings.SettingsCommandButton.NewButton.Text = @Resources.MainResource.New;
        settings.SettingsCommandButton.EditButton.Text = " ";
        
        settings.SettingsCommandButton.EditButton.Styles.Style.CssClass = "fa fa fa-pencil";
        settings.SettingsCommandButton.DeleteButton.Text = " ";
        settings.SettingsCommandButton.DeleteButton.Styles.Style.CssClass = "fa fa-trash-o";
        settings.SettingsCommandButton.CancelButton.Text = @Resources.MainResource.Cancel;
        settings.SettingsCommandButton.ClearFilterButton.Text = @Resources.MainResource.Clear;
        settings.SettingsCommandButton.UpdateButton.Text = @Resources.MainResource.Save;
        settings.SettingsCommandButton.UpdateButton.ButtonType = GridViewCommandButtonType.Button;
        settings.SettingsCommandButton.CancelButton.ButtonType = GridViewCommandButtonType.Button;
        settings.CommandColumn.Width = new System.Web.UI.WebControls.Unit("60px");
        settings.CommandColumn.Visible = true;
        
        settings.CommandColumn.ShowNewButton = false;
        settings.CommandColumn.ShowDeleteButton = false ;
        

        settings.SettingsText.CommandClearSearchPanelFilter = @Resources.MainResource.Clear;
        settings.SettingsText.SearchPanelEditorNullText = @Resources.MainResource.SearchNullText;
        settings.SettingsText.ConfirmDelete = @Resources.MainResource.DeleteMessage;
        settings.SettingsText.EmptyDataRow = @Resources.MainResource.NoData;
        settings.SettingsPager.Summary.Text = Resources.MainResource.PageSummaryText;
        
        settings.SettingsPopup.EditForm.Width = new System.Web.UI.WebControls.Unit("350px");
        settings.SettingsPopup.EditForm.Modal = true;
        settings.SettingsPopup.EditForm.CloseOnEscape = AutoBoolean.True;
        settings.SettingsPopup.EditForm.HorizontalAlign = PopupHorizontalAlign.WindowCenter;
        settings.SettingsPopup.EditForm.VerticalAlign = PopupVerticalAlign.WindowCenter;


        settings.Width = new System.Web.UI.WebControls.Unit("100%");
        settings.RightToLeft = DefaultBoolean.True;
        settings.SettingsPager.Visible = true;
        //settings.Settings.ShowFilterRow = true;
        settings.SettingsBehavior.AllowSelectByRowClick = true;
        settings.Styles.AlternatingRow.BackColor = System.Drawing.Color.FromName("#f9f9f9");
        //settings.TotalSummary.Add(DevExpress.Data.SummaryItemType.Sum, "NumberofBooksPerModel").DisplayFormat = "n0";
        //settings.TotalSummary.Add(DevExpress.Data.SummaryItemType.Sum, "PackageTotalPerModel").DisplayFormat = "n0";
        //settings.TotalSummary.Add(DevExpress.Data.SummaryItemType.Sum, "PackageTotal").DisplayFormat = "n0";
        //settings.Settings.ShowFooter = true;
                settings.Columns.Add(column =>
                {
                    column.FieldName = "PackagingTypeName";
                    column.EditFormSettings.ColumnSpan = 2;
                    column.VisibleIndex = 1;
                    column.Caption = @Resources.ModelResource.PackagingTypeName;
                    column.Width = new System.Web.UI.WebControls.Unit("20%");
                    column.CellStyle.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Right;
                    column.ColumnType = MVCxGridViewColumnType.TextBox;
                    

                });
                settings.Columns.Add(column =>
                {
                    column.FieldName = "CalculationTypeName";
                    column.EditFormSettings.ColumnSpan = 2;
                    column.VisibleIndex = 2;
                    column.Caption = @Resources.ModelResource.PackingCalculationTypeName;
                    column.Width = new System.Web.UI.WebControls.Unit("20%");
                    column.CellStyle.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Right;
                    column.ColumnType = MVCxGridViewColumnType.TextBox;

                });
                
				
                settings.Columns.Add(column =>
                {
                    column.FieldName = "PackingValue";
                    column.EditFormSettings.ColumnSpan = 2;
                    column.VisibleIndex = 4;
                    column.Caption = @Resources.ModelResource.PackingValue;
                    column.Name = "PackingValue";

                    column.Width = new System.Web.UI.WebControls.Unit("60px");
                    column.ColumnType = MVCxGridViewColumnType.SpinEdit;
                    var textProperties = column.PropertiesEdit as SpinEditProperties;
                    textProperties.ValidationSettings.RequiredField.IsRequired = true;
                    textProperties.ValidationSettings.RequiredField.ErrorText = "*";
                    textProperties.ValidationSettings.Display = Display.Dynamic;
                    textProperties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.Text;
                    textProperties.Width = new System.Web.UI.WebControls.Unit("100px");
                    textProperties.NumberType = SpinEditNumberType.Integer;
                });

                
				
                settings.Columns.Add(column =>
                {
                    column.FieldName = "RepackCount";
                    column.EditFormSettings.ColumnSpan = 2;
                    column.VisibleIndex = 7;                    
                    column.EditFormSettings.Visible = DefaultBoolean.False;
                    column.EditFormSettings.VisibleIndex = -1;
                    column.Caption = @Resources.ModelResource.PackageTotal;
                    column.Name = "RepackCount";
                    column.ReadOnly = true;
                    column.Width = new System.Web.UI.WebControls.Unit("60px");
                    column.ColumnType = MVCxGridViewColumnType.SpinEdit;
                    
                    var textProperties = column.PropertiesEdit as SpinEditProperties;
                    //textProperties.ValidationSettings.RequiredField.IsRequired = true;
                    //textProperties.ValidationSettings.RequiredField.ErrorText = "*";
                    //textProperties.ValidationSettings.Display = Display.Dynamic;
                    //textProperties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.Text;
                    textProperties.Width = new System.Web.UI.WebControls.Unit("100px");
                    textProperties.NumberType = SpinEditNumberType.Integer;
                });
			});
		if (ViewData["EditError"] != null){
        grid.SetEditErrorText((string)ViewData["EditError"]);
    }
}
@grid.Bind(Model).GetHtml()