QiyasPlatform/Qiyas.WebAdmin/Controllers/BookRePackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DevExpress.Web.Mvc;
using System.Text;

namespace Qiyas.WebAdmin.Controllers
{
    [Authorize]
    public class BookRePackController : Controller
    {
        public int PrintingOperationID
        {
            set
            {
                var key = "34FAA431-CF79-4869-9488-93F6BBE81263";
                var Session = HttpContext.Session;
                Session[key] = value;
            }
            get
            {
                var key = "34FAA431-CF79-4869-9488-93F6BBE81263";
                var Session = HttpContext.Session;
                if (Session[key] == null)
                    Session[key] = 0;
                return (int)Session[key];
            }
        }


        public List<BusinessLogicLayer.Entity.PPM.BookRepackPackageItem> BookRepackPackageItemList
        {
            set
            {
                var key = "34FAA431-CF79-4869-1234-93F6BBE81263";
                var Session = HttpContext.Session;
                Session[key] = value;
            }
            get
            {
                var key = "34FAA431-CF79-4869-1234-93F6BBE81263";
                var Session = HttpContext.Session;
                if (Session[key] == null)
                    Session[key] = new List< BusinessLogicLayer.Entity.PPM.BookRepackPackageItem>();
                return  Session[key] as List< BusinessLogicLayer.Entity.PPM.BookRepackPackageItem>;
            }
        }

        public List<BusinessLogicLayer.Entity.PPM.BookPackItemOperation> BookPackItemOperationList
        {
            set
            {
                var key = "34FAA431-CF79-4869-1235-93F6BBE81263";
                var Session = HttpContext.Session;
                Session[key] = value;
            }
            get
            {
                var key = "34FAA431-CF79-4869-1235-93F6BBE81263";
                var Session = HttpContext.Session;
                if (Session[key] == null)
                    Session[key] = new List<BusinessLogicLayer.Entity.PPM.BookPackItemOperation>();
                return Session[key] as List<BusinessLogicLayer.Entity.PPM.BookPackItemOperation>;
            }
        }


        public int PackID
        {
            set
            {
                var key = "34FAA431-CF79-4869-9488-93F6AAE83621";
                var Session = HttpContext.Session;
                Session[key] = value;
            }
            get
            {
                var key = "34FAA431-CF79-4869-9488-93F6AAE83621";
                var Session = HttpContext.Session;
                if (Session[key] == null)
                    Session[key] = 0;
                return (int)Session[key];
            }
        }

        // GET: BookRePack
        public ActionResult Index()
        {
            BusinessLogicLayer.Entity.PPM.BookPrintingOperation printing = new BusinessLogicLayer.Entity.PPM.BookPrintingOperation();
            BookPackItemOperationList = new List<BusinessLogicLayer.Entity.PPM.BookPackItemOperation>();
            BookRepackPackageItemList = new List<BusinessLogicLayer.Entity.PPM.BookRepackPackageItem>();
            return View(printing);
        }

        public ActionResult LoadPack(string serial)
        {
            return Json("");
        }

        #region Old Grid Events
        [ValidateInput(false)]
        public ActionResult RepackGridViewPartial()
        {
            var model = new object[0];
            return PartialView("_RepackGridViewPartial", model);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult RepackGridViewPartialAddNew([ModelBinder(typeof(DevExpressEditorsBinder))] Qiyas.BusinessLogicLayer.Entity.PPM.BookPackingOperation item)
        {
            var model = new object[0];
            if (ModelState.IsValid)
            {
                try
                {
                    // Insert here a code to insert the new item in your model
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
                ViewData["EditError"] = "Please, correct all errors.";
            return PartialView("_RepackGridViewPartial", model);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult RepackGridViewPartialUpdate([ModelBinder(typeof(DevExpressEditorsBinder))] Qiyas.BusinessLogicLayer.Entity.PPM.BookPackingOperation item)
        {
            var model = new object[0];
            if (ModelState.IsValid)
            {
                try
                {
                    // Insert here a code to update the item in your model
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
                ViewData["EditError"] = "Please, correct all errors.";
            return PartialView("_RepackGridViewPartial", model);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult RepackGridViewPartialDelete(System.Int32 BookPackingOperationID)
        {
            var model = new object[0];
            if (BookPackingOperationID >= 0)
            {
                try
                {
                    // Insert here a code to delete the item from your model
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            return PartialView("_RepackGridViewPartial", model);
        }

        #endregion


        #region Grid Operations
        [ValidateInput(false)]
        public ActionResult PackingGridViewPartial()
        {

            var model = BookPackItemOperationList;//new BusinessLogicLayer.Components.PPM.BookPackItemOperationLogic().GetByBookPackID(PackID);
            return PartialView("_RepackGridViewPartial", model);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult PackingGridViewPartialAddNew([ModelBinder(typeof(DevExpressEditorsBinder))] Qiyas.BusinessLogicLayer.Entity.PPM.BookPackItemOperation item)
        {

            //if (ModelState.IsValid)
            {
                try
                {
                    bool isValid = true;
                    if (BookRepackPackageItemList.Count == 0)
                    {
                        ViewData["EditError"] = Resources.MainResource.NoRepackItemsSelected;
                        isValid = false;
                        var modelError = new BusinessLogicLayer.Components.PPM.BookPackItemOperationLogic().GetByBookPackID(PackID);
                        return PartialView("_RepackGridViewPartial", modelError);
                    }
                    if (item.PackingCalculationTypeID == 2)
                    {
                        if (item.PackingParentID == 0)
                        {
                            ViewData["EditError"] = Resources.MainResource.EnterPackingParentID;
                            isValid = false;
                        }
                    }

                    
                    int totalPackage = TotalPackages(item);
                    BusinessLogicLayer.Entity.PPM.BookPackItem packItem = new BusinessLogicLayer.Entity.PPM.BookPackItem(PackID);
                    BusinessLogicLayer.Entity.PPM.BookPackingOperation package = new BusinessLogicLayer.Entity.PPM.BookPackingOperation(packItem.BookPackingOperationID.Value);
                    BusinessLogicLayer.Entity.PPM.BookPrintingOperation printingOperation = new BusinessLogicLayer.Entity.PPM.BookPrintingOperation(PrintingOperationID);
                    BusinessLogicLayer.Entity.PPM.PackagingType ptype = new BusinessLogicLayer.Entity.PPM.PackagingType(item.PackagingTypeID.Value);
                    
                    if (printingOperation != null)
                    {
                        BusinessLogicLayer.Components.PPM.BookPackItemOperationLogic logic = new BusinessLogicLayer.Components.PPM.BookPackItemOperationLogic();

                        int totalItems = GetTotalBooksForModel(true);
                        int currentTotal = ptype.BooksPerPackage == 3 && ptype.ExamModelCount == 1 ? GetTotalItemsA3() : GetTotalItems();
                        int totalPrint = (totalPackage * ptype.BooksPerPackage.Value + currentTotal);
                        int count = new BusinessLogicLayer.Components.PPM.ExamLogic().GetExamModelCount(printingOperation.ExamID.Value);
                        if (count > 1)
                        {
                            totalItems = totalItems * count;
                        }
                        if (totalItems < totalPrint)
                        {
                            isValid = false;
                            ViewData["EditError"] = Resources.MainResource.TotalPackGreaterThanOverallTotal;
                        }
                    }
                    if (isValid)
                    {
                        BusinessLogicLayer.Entity.PPM.BookPackItemOperation entity = new BusinessLogicLayer.Entity.PPM.BookPackItemOperation();
                        entity.BookPackItemOperationID = BookPackItemOperationList.Count + 1;
                        entity.AllocatedFrom = item.AllocatedFrom;
                        entity.BookPackItemID = packItem.BookPackItemID;
                        entity.PackingParentID = package.BookPackingOperationID;
                        entity.CreatedDate = DateTime.Now;
                        entity.ModifiedDate = DateTime.Now;
                        entity.Name = item.Name;
                        entity.PackingParentID = package.PackageTotal;
                        entity.PackageTotal = totalPackage;
                        entity.PackagingTypeID = item.PackagingTypeID;

QiyasPlatform/Qiyas.WebAdmin/Views/BookRePack/Index.cshtml
@model Qiyas.BusinessLogicLayer.Entity.PPM.BookPrintingOperation

@{
    ViewBag.Title = Resources.MainResource.BookRepack;
}

<div class="page-title">
    <h1>
        @Resources.MainResource.BookRepack
    </h1>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="widget-container fluid-height clearfix">
            <div class="widget-content padded clearfix">
                @using (Html.BeginForm("Repack", "BookRePack", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    @Html.AntiForgeryToken()
    <div class="col-lg-4 pull-right">
        @Html.ValidationSummary("", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.PackNumber, new { @class = "col-md-5  pull-right control-label" })
            <div class="col-md-4  pull-right">
                @Html.TextBoxFor(m => m.PackNumber, new { @class = "form-control" })
            </div>
            <div class="error" style="color: forestgreen;display:none;" id="packageExists">حزمة صحيحة</div>
            <div class="error" style="color: darkred;display:none;" id="packageDoesntExist">لا يمكن تعديل هذه الحزمة</div>
        </div>
        <br /><br />
        

        </div>
                    
                    @Html.Action("RepackPackageGridViewPartial")

                    <br /><br />
        @Html.Action("RepackGridViewPartial")
        <br /><br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" name="Save" value="إعادة تحزيم" class="btn btn-default btn-primary" />

            </div>
        </div>
        }
    </div>
        </div>
    </div>
</div>



@section Scripts {
    <script type="text/javascript">
        $("#SavePack").click(function () {
            var r = confirm("هل تريد إعادة التحزيم");
            if (r == true) {
                var form = $("form#packForm");
                form.attr("action", "@Url.Action("NumberingPack", "BookRePack")");
                form.submit();
            } else {
                e.preventDefault();
                return false;
            }

    });

        $("#PackNumber").change(function () {
            var urlLink = "@Url.Action("CheckItem", "BookRePack")";

            $.ajax({
                type: "POST",
                dataType: "json",
                data:  {
                    item: $('#PackNumber').val()
                },
                url: urlLink,
                success: function (data) {
                    if (data == "exists") {
                        RepackPackageGridView.PerformCallback();
                        $("#PackNumber").val('');
                        $('#packageDoesntExist').hide();
                        $('#packageExists').fadeIn('slow', function () {
                            $(this).delay(2000).fadeOut('slow');
                        });
                    }
                    else {
                        $('#packageExists').hide();
                        $('#packageDoesntExist').show();
                    }

                },
                error: function (data) {
                    $('#packageExists').hide();
                    $('#packageDoesntExist').show();
                }
            });
        });
        $("#BackButton").click(function (e) {
            e.preventDefault();
            window.location = "/BookPrintingOperation";
            return false;
            @*var form = $("form#packForm");
            form.attr("action", "@Url.Action("PrinPacks", "BookPackingOperation", Qiyas.WebAdmin.Controllers.BookPackingOperationController.MainID)");
            form.submit();*@
        });
    </script>
}

QiyasPlatform/Qiyas.WebAdmin/Views/BookRePack/_RepackGridViewPartial.cshtml
@using Qiyas.WebAdmin.Common.Helpers

@{
    var grid = Html.DevExpress().GridView(settings =>
    {
        settings.Name = "gridRepack";
        settings.CallbackRouteValues = new { Controller = "BookRePack", Action = "PackingGridViewPartial" };

        settings.SettingsEditing.AddNewRowRouteValues = new { Controller = "BookRePack", Action = "PackingGridViewPartialAddNew" };
        //settings.SettingsEditing.UpdateRowRouteValues = new { Controller = "BookRePack", Action = "PackingGridViewPartialUpdate" };
        settings.SettingsEditing.DeleteRowRouteValues = new { Controller = "BookRePack", Action = "PackingGridViewPartialDelete" };
        settings.KeyFieldName = "BookPackItemOperationID";


        settings.SettingsBehavior.ConfirmDelete = true;
        settings.SettingsEditing.Mode = GridViewEditingMode.Inline;

        settings.CommandColumn.ShowNewButtonInHeader = true;
        settings.SettingsCommandButton.NewButton.Text = @Resources.MainResource.New;
        settings.SettingsCommandButton.EditButton.Text = " ";

        settings.SettingsCommandButton.EditButton.Styles.Style.CssClass = "fa fa fa-pencil";
        settings.SettingsCommandButton.DeleteButton.Text = " ";
        settings.SettingsCommandButton.DeleteButton.Styles.Style.CssClass = "fa fa-trash-o";
        settings.SettingsCommandButton.CancelButton.Text = @Resources.MainResource.Cancel;
        settings.SettingsCommandButton.ClearFilterButton.Text = @Resources.MainResource.Clear;
        settings.SettingsCommandButton.UpdateButton.Text = @Resources.MainResource.Save;
        settings.SettingsCommandButton.UpdateButton.ButtonType = GridViewCommandButtonType.Button;
        settings.SettingsCommandButton.CancelButton.ButtonType = GridViewCommandButtonType.Button;
        settings.CommandColumn.Width = new System.Web.UI.WebControls.Unit("60px");
        settings.CommandColumn.Visible = true;
        settings.CommandColumn.ShowNewButton = false;
        settings.CommandColumn.ShowDeleteButton = true;
        //settings.CommandColumn.ShowEditButton = true;

        //settings.SettingsSearchPanel.Visible = true;
        //settings.SettingsSearchPanel.ShowClearButton = true;
        //settings.Styles.SearchPanel.CssClass = "dxgvSearchPanel_MetropolisBlue search_devexpress";

        settings.SettingsText.CommandClearSearchPanelFilter = @Resources.MainResource.Clear;
        settings.SettingsText.SearchPanelEditorNullText = @Resources.MainResource.SearchNullText;
        settings.SettingsText.ConfirmDelete = @Resources.MainResource.DeleteMessage;
        settings.SettingsText.EmptyDataRow = @Resources.MainResource.NoData;
        settings.SettingsPager.Summary.Text = Resources.MainResource.PageSummaryText;

        settings.SettingsPopup.EditForm.Width = new System.Web.UI.WebControls.Unit("350px");
        settings.SettingsPopup.EditForm.Modal = true;
        settings.SettingsPopup.EditForm.CloseOnEscape = AutoBoolean.True;
        settings.SettingsPopup.EditForm.HorizontalAlign = PopupHorizontalAlign.WindowCenter;
        settings.SettingsPopup.EditForm.VerticalAlign = PopupVerticalAlign.WindowCenter;


        settings.Width = new System.Web.UI.WebControls.Unit("100%");
        settings.RightToLeft = DefaultBoolean.True;
        settings.SettingsPager.Visible = true;
        //settings.Settings.ShowFilterRow = true;
        settings.SettingsBehavior.AllowSelectByRowClick = true;
        settings.Styles.AlternatingRow.BackColor = System.Drawing.Color.FromName("#f9f9f9");


        settings.Columns.Add(column =>
        {
            column.FieldName = "PackagingTypeID";
            column.EditFormSettings.ColumnSpan = 2;
            column.VisibleIndex = 1;
            column.Caption = @Resources.ModelResource.PackagingTypeName;
            column.Width = new System.Web.UI.WebControls.Unit("20%");
            column.CellStyle.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Right;
            column.ColumnType = MVCxGridViewColumnType.ComboBox;

            var comboProperties = column.PropertiesEdit as ComboBoxProperties;
            comboProperties.DataSource = (new Qiyas.BusinessLogicLayer.Components.PPM.PackagingTypeLogic().GetAllForPrint(Qiyas.WebAdmin.Controllers.BookPackingOperationController.MainID));
            comboProperties.TextField = "Name";
            comboProperties.ValueField = "PackagingTypeID";

            comboProperties.ValueType = typeof(int);
            comboProperties.ValidationSettings.RequiredField.IsRequired = true;
            comboProperties.ValidationSettings.RequiredField.ErrorText = "*";
            comboProperties.ValidationSettings.Display = Display.Dynamic;
            comboProperties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.Text;

        });
        settings.Columns.Add(column =>
        {
            column.FieldName = "PackingCalculationTypeID";
            column.EditFormSettings.ColumnSpan = 2;
            column.VisibleIndex = 2;
            column.Caption = @Resources.ModelResource.PackingCalculationTypeName;
            column.Width = new System.Web.UI.WebControls.Unit("20%");
            column.CellStyle.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Right;
            column.ColumnType = MVCxGridViewColumnType.ComboBox;

            var comboProperties = column.PropertiesEdit as ComboBoxProperties;
            comboProperties.DataSource = (new Qiyas.BusinessLogicLayer.Components.PPM.PackingCalculationTypeLogic().GetAll());
            comboProperties.TextField = "Name";
            comboProperties.ValueField = "PackingCalculationTypeID";

            comboProperties.ValueType = typeof(int);
            comboProperties.ValidationSettings.RequiredField.IsRequired = true;
            comboProperties.ValidationSettings.RequiredField.ErrorText = "*";
            comboProperties.ValidationSettings.Display = Display.Dynamic;
            comboProperties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.Text;

        });
        settings.Columns.Add(column =>
        {
            column.FieldName = "PackingParentID";
            column.VisibleIndex = 3;
            column.EditFormSettings.ColumnSpan = 2;
            column.Width = new System.Web.UI.WebControls.Unit("20%");
            column.Caption = @Resources.ModelResource.AllocatedFrom;
            column.ColumnType = MVCxGridViewColumnType.ComboBox;
            var comboProperties = column.PropertiesEdit as ComboBoxProperties;
            comboProperties.DataSource = (new Qiyas.BusinessLogicLayer.Components.PPM.BookPackItemOperationLogic().GetPackagingTypeByBookPackID(Qiyas.WebAdmin.Controllers.BookPackingOperationController.MainID));
            comboProperties.TextField = "PackagingTypeName";
            comboProperties.ValueField = "BookPackingOperationID";

            comboProperties.ValueType = typeof(int);
        });

        settings.Columns.Add(column =>
        {
            column.FieldName = "PackingValue";
            column.EditFormSettings.ColumnSpan = 2;
            column.VisibleIndex = 4;
            column.Caption = @Resources.ModelResource.PackingValue;
            column.Name = "PackingValue";

            column.Width = new System.Web.UI.WebControls.Unit("60px");
            column.ColumnType = MVCxGridViewColumnType.SpinEdit;
            var textProperties = column.PropertiesEdit as SpinEditProperties;
            textProperties.ValidationSettings.RequiredField.IsRequired = true;
            textProperties.ValidationSettings.RequiredField.ErrorText = "*";
            textProperties.ValidationSettings.Display = Display.Dynamic;
            textProperties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.Text;
            textProperties.Width = new System.Web.UI.WebControls.Unit("100px");
            textProperties.NumberType = SpinEditNumberType.Integer;
        });

        settings.Columns.Add(column =>
        {
            column.FieldName = "PackageTotal";
            column.EditFormSettings.ColumnSpan = 2;
            column.VisibleIndex = 5;
            column.EditFormSettings.Visible = DefaultBoolean.False;
            column.EditFormSettings.VisibleIndex = -1;
            column.Caption = @Resources.ModelResource.PackageTotal;
            column.Name = "PackageTotal";
            column.ReadOnly = true;
            column.Width = new System.Web.UI.WebControls.Unit("60px");
            column.ColumnType = MVCxGridViewColumnType.SpinEdit;
            var textProperties = column.PropertiesEdit as SpinEditProperties;
            //textProperties.ValidationSettings.RequiredField.IsRequired = true;
            //textProperties.ValidationSettings.RequiredField.ErrorText = "*";
            //textProperties.ValidationSettings.Display = Display.Dynamic;
            //textProperties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.Text;
            textProperties.Width = new System.Web.UI.WebControls.Unit("100px");
            textProperties.NumberType = SpinEditNumberType.Integer;
        });
    });
    if (ViewData["EditError"] != null)
    {
        grid.SetEditErrorText((string)ViewData["EditError"]);
    }
}
@grid.Bind(Model).GetHtml()

QiyasPlatform/Qiyas.WebAdmin/Views/BookRePack/_RepackPackageGridViewPartial.cshtml
@{
	var grid = Html.DevExpress().GridView(settings => {
        settings.Name = "RepackPackageGridView";
        settings.CallbackRouteValues = new { Controller = "BookRePack", Action = "RepackPackageGridViewPartial" };

				settings.SettingsEditing.AddNewRowRouteValues = new { Controller = "BookRePack", Action = "RepackPackageGridViewPartialAddNew" };
        settings.SettingsEditing.UpdateRowRouteValues = new { Controller = "BookRePack", Action = "RepackPackageGridViewPartialUpdate" };
        settings.SettingsEditing.DeleteRowRouteValues = new { Controller = "BookRePack", Action = "RepackPackageGridViewPartialDelete" };
        settings.KeyFieldName = "BookPackItemID";


        settings.SettingsBehavior.ConfirmDelete = true;
        settings.SettingsEditing.Mode = GridViewEditingMode.Inline;

        settings.CommandColumn.ShowNewButtonInHeader = false;
        settings.SettingsCommandButton.NewButton.Text = @Resources.MainResource.New;
        settings.SettingsCommandButton.EditButton.Text = " ";

        settings.SettingsCommandButton.EditButton.Styles.Style.CssClass = "fa fa fa-pencil";
        settings.SettingsCommandButton.DeleteButton.Text = " ";
        settings.SettingsCommandButton.DeleteButton.Styles.Style.CssClass = "fa fa-trash-o";
        settings.SettingsCommandButton.CancelButton.Text = @Resources.MainResource.Cancel;
        settings.SettingsCommandButton.ClearFilterButton.Text = @Resources.MainResource.Clear;
        settings.SettingsCommandButton.UpdateButton.Text = @Resources.MainResource.Save;
        settings.SettingsCommandButton.UpdateButton.ButtonType = GridViewCommandButtonType.Button;
        settings.SettingsCommandButton.CancelButton.ButtonType = GridViewCommandButtonType.Button;
        settings.CommandColumn.Width = new System.Web.UI.WebControls.Unit("60px");
        settings.CommandColumn.Visible = true;
        settings.CommandColumn.ShowNewButton = false;
        settings.CommandColumn.ShowDeleteButton = true;
        //settings.CommandColumn.ShowEditButton = true;

        //settings.SettingsSearchPanel.Visible = true;
        //settings.SettingsSearchPanel.ShowClearButton = true;
        //settings.Styles.SearchPanel.CssClass = "dxgvSearchPanel_MetropolisBlue search_devexpress";

        settings.SettingsText.CommandClearSearchPanelFilter = @Resources.MainResource.Clear;
        settings.SettingsText.SearchPanelEditorNullText = @Resources.MainResource.SearchNullText;
        settings.SettingsText.ConfirmDelete = @Resources.MainResource.DeleteMessage;
        settings.SettingsText.EmptyDataRow = @Resources.MainResource.NoData;
        settings.SettingsPager.Summary.Text = Resources.MainResource.PageSummaryText;

        settings.SettingsPopup.EditForm.Width = new System.Web.UI.WebControls.Unit("350px");
        settings.SettingsPopup.EditForm.Modal = true;
        settings.SettingsPopup.EditForm.CloseOnEscape = AutoBoolean.True;
        settings.SettingsPopup.EditForm.HorizontalAlign = PopupHorizontalAlign.WindowCenter;
        settings.SettingsPopup.EditForm.VerticalAlign = PopupVerticalAlign.WindowCenter;


        settings.Width = new System.Web.UI.WebControls.Unit("100%");
        settings.RightToLeft = DefaultBoolean.True;
        settings.SettingsPager.Visible = true;
        //settings.Settings.ShowFilterRow = true;
        settings.SettingsBehavior.AllowSelectByRowClick = true;
        settings.Styles.AlternatingRow.BackColor = System.Drawing.Color.FromName("#f9f9f9");


                settings.Columns.Add(column =>
                {
                    column.FieldName = "ExamCode";
                    column.VisibleIndex = 1;
                    column.EditFormSettings.ColumnSpan = 2;
                    column.Caption = @Resources.ModelResource.ExamCode;

                    column.ColumnType = MVCxGridViewColumnType.TextBox;
                    var textProperties = column.PropertiesEdit as TextBoxProperties;
                    textProperties.ValidationSettings.RequiredField.IsRequired = true;
                    textProperties.ValidationSettings.RequiredField.ErrorText = "*";
                    textProperties.ValidationSettings.Display = Display.Dynamic;
                    textProperties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.Text;
                });
				
                settings.Columns.Add(column =>
                {
                    column.FieldName = "ExamModelName";
                    column.VisibleIndex = 2;
                    column.EditFormSettings.ColumnSpan = 2;
                    column.Caption = @Resources.ModelResource.ExamModelNames;

                    column.ColumnType = MVCxGridViewColumnType.TextBox;
                    var textProperties = column.PropertiesEdit as TextBoxProperties;
                    textProperties.ValidationSettings.RequiredField.IsRequired = true;
                    textProperties.ValidationSettings.RequiredField.ErrorText = "*";
                    textProperties.ValidationSettings.Display = Display.Dynamic;
                    textProperties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.Text;
                });
				
                settings.Columns.Add(column =>
                {
                    column.FieldName = "BooksCount";
                    column.VisibleIndex = 3;
                    column.EditFormSettings.ColumnSpan = 2;
                    column.Caption = @Resources.ModelResource.BooksTotal;

                    column.ColumnType = MVCxGridViewColumnType.TextBox;
                    var textProperties = column.PropertiesEdit as TextBoxProperties;
                    textProperties.ValidationSettings.RequiredField.IsRequired = true;
                    textProperties.ValidationSettings.RequiredField.ErrorText = "*";
                    textProperties.ValidationSettings.Display = Display.Dynamic;
                    textProperties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.Text;
                });
                settings.Columns.Add(column =>
                {
                    column.FieldName = "PackSerial";
                    column.VisibleIndex = 4;
                    column.EditFormSettings.ColumnSpan = 2;
                    column.Caption = @Resources.ModelResource.PackSerial;

                    column.ColumnType = MVCxGridViewColumnType.TextBox;
                    var textProperties = column.PropertiesEdit as TextBoxProperties;
                    textProperties.ValidationSettings.RequiredField.IsRequired = true;
                    textProperties.ValidationSettings.RequiredField.ErrorText = "*";
                    textProperties.ValidationSettings.Display = Display.Dynamic;
                    textProperties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.Text;
                });
			});
		if (ViewData["EditError"] != null){
        grid.SetEditErrorText((string)ViewData["EditError"]);
    }
}
@grid.Bind(Model).GetHtml()