QiyasPlatform/Qiyas.WebAdmin/Controllers/BookPrintingOperationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DevExpress.Web.Mvc;
using System.Text;

namespace Qiyas.WebAdmin.Controllers
{
    public enum OperationStatus
    {
        Printing = 1,
        Packing = 2
    }
    [Authorize]
    public class BookPrintingOperationController : Controller
    {
        // GET: BookPrintingOperation
        public ActionResult Index()
        {
            return View();
        }

        #region Grid View Events
        BusinessLogicLayer.Components.PPM.BookPrintingOperationLogic BookPrintingOperationLogic = new BusinessLogicLayer.Components.PPM.BookPrintingOperationLogic();
        BusinessLogicLayer.Components.PPM.BookPackingOperationLogic BookPackingOperationLogic = new BusinessLogicLayer.Components.PPM.BookPackingOperationLogic();
        [ValidateInput(false)]
        public ActionResult BookPrintingOperationGridViewPartial()
        {
            var model = new BusinessLogicLayer.Components.PPM.BookPrintingOperationLogic().GetAll();
            return PartialView("_BookPrintingOperationGridViewPartial", model);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult BookPrintingOperationGridViewPartialAddNew([ModelBinder(typeof(DevExpressEditorsBinder))] Qiyas.BusinessLogicLayer.Entity.PPM.BookPrintingOperation item)
        {
            
            if (ModelState.IsValid)
            {
                try
                {
                    if((item.ExamsNeededForA3.Value % 3) != 0)
                    {
                        ViewData["EditError"] = "يجب ان يكون الايه 3 من مضاعفات الثلاثة";
                    }
                    else
                    {
                        BusinessLogicLayer.Entity.PPM.BookPrintingOperation printing = new BusinessLogicLayer.Entity.PPM.BookPrintingOperation();
                        printing.ExamsNeededForA3 = item.ExamsNeededForA3;
                        printing.ExamsNeededForA4 = item.ExamsNeededForA4;
                        printing.ExamsNeededForCD = item.ExamsNeededForCD;
                        printing.ExamID = item.ExamID;
                        printing.Name = item.Name;
                        printing.OperationStatusID = (int)OperationStatus.Printing;
                        printing.PrintsForOneModel = item.PrintsForOneModel;
                        printing.ModifiedDate = DateTime.Now;
                        printing.CreatedDate = DateTime.Now;
                        printing.Save();

                        if(!BookPackingOperationLogic.HaveA3Packs(printing.BookPrintingOperationID) && printing.ExamsNeededForA3 > 0)
                        {
                            BusinessLogicLayer.Entity.PPM.BookPackingOperation pack = new BusinessLogicLayer.Entity.PPM.BookPackingOperation();
                            BusinessLogicLayer.Entity.PPM.Exam exam = new BusinessLogicLayer.Entity.PPM.Exam(printing.ExamID.Value);
                            BusinessLogicLayer.Entity.PPM.PackagingType ptype = new BusinessLogicLayer.Entity.PPM.PackagingType(1, 3);
                            if(ptype.HasObject)
                            {
                                pack.BookPrintingOperationID = printing.BookPrintingOperationID;
                                pack.CreatedDate = DateTime.Now;
                                pack.ModifiedDate = DateTime.Now;
                                pack.NumberofBooksPerModel = printing.ExamsNeededForA3;
                                pack.PackageTotalPerModel = printing.ExamsNeededForA3 / 3;
                                //pack.PackageTotal = pack.PackageTotalPerModel * exam.ExamModels.Count;
                                pack.PackageTotal = pack.PackageTotalPerModel;
                                pack.PackagingTypeID = ptype.PackagingTypeID;
                                pack.PackingCalculationTypeID = 1;
                                pack.PackingValue = 100;
                                pack.Save();
                            }
                            
                        }
                    }
                    
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
                ViewData["EditError"] = Resources.MainResource.PleaseCorrectErrors;
            var model = new BusinessLogicLayer.Components.PPM.BookPrintingOperationLogic().GetAll();
            return PartialView("_BookPrintingOperationGridViewPartial", model);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult BookPrintingOperationGridViewPartialUpdate([ModelBinder(typeof(DevExpressEditorsBinder))] Qiyas.BusinessLogicLayer.Entity.PPM.BookPrintingOperation item)
        {
            
            if (ModelState.IsValid)
            {
                try
                {
                    if(item.OperationStatusID > 1)
                    {
                        ViewData["EditError"] = "حالة الطلب يجب ان تكون طباعة للسماح بالتعديل";
                        var modelErr = new BusinessLogicLayer.Components.PPM.BookPrintingOperationLogic().GetAll();
                        return PartialView("_BookPrintingOperationGridViewPartial", modelErr);
                    }
                    BusinessLogicLayer.Entity.PPM.BookPrintingOperation printing = new BusinessLogicLayer.Entity.PPM.BookPrintingOperation(item.BookPrintingOperationID);
                    printing.ExamsNeededForA3 = item.ExamsNeededForA3;
                    printing.ExamsNeededForA4 = item.ExamsNeededForA4;
                    printing.ExamsNeededForCD = item.ExamsNeededForCD;
                    printing.ExamID = item.ExamID;
                    printing.Name = item.Name;
                    printing.PrintsForOneModel = item.PrintsForOneModel;
                    printing.ModifiedDate = DateTime.Now;
                    printing.CreatedDate = DateTime.Now;
                    printing.Save();

                    if (!BookPackingOperationLogic.HaveA3Packs(printing.BookPrintingOperationID))
                    {
                        BusinessLogicLayer.Entity.PPM.BookPackingOperation pack = new BusinessLogicLayer.Entity.PPM.BookPackingOperation();
                        BusinessLogicLayer.Entity.PPM.Exam exam = new BusinessLogicLayer.Entity.PPM.Exam(printing.ExamID.Value);
                        BusinessLogicLayer.Entity.PPM.PackagingType ptype = new BusinessLogicLayer.Entity.PPM.PackagingType(1, 3);
                        if (ptype.HasObject)
                        {
                            pack.BookPrintingOperationID = printing.BookPrintingOperationID;
                            pack.CreatedDate = DateTime.Now;
                            pack.ModifiedDate = DateTime.Now;
                            pack.NumberofBooksPerModel = printing.ExamsNeededForA3;
                            pack.PackageTotalPerModel = printing.ExamsNeededForA3 / 3;
                            pack.PackageTotal = pack.PackageTotalPerModel * exam.ExamModels.Count;
                            pack.PackagingTypeID = ptype.PackagingTypeID;
                            pack.PackingCalculationTypeID = 1;
                            pack.PackingValue = 100;
                            pack.Save();
                        }

                    }
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
                ViewData["EditError"] = "Please, correct all errors.";
            var model = new BusinessLogicLayer.Components.PPM.BookPrintingOperationLogic().GetAll();
            return PartialView("_BookPrintingOperationGridViewPartial", model);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult BookPrintingOperationGridViewPartialDelete(System.Int32 BookPrintingOperationID)
        {
            
            if (BookPrintingOperationID >= 0)
            {
                try
                {
                    BusinessLogicLayer.Components.PPM.BookPrintingOperationLogic logic = new BusinessLogicLayer.Components.PPM.BookPrintingOperationLogic();
                    if (!logic.HasDependencies(BookPrintingOperationID))
                    {
                        BusinessLogicLayer.Entity.PPM.BookPrintingOperation type = new BusinessLogicLayer.Entity.PPM.BookPrintingOperation(BookPrintingOperationID);
                        if (type.OperationStatusID <= 3 || type.OperationStatusID == 8)
                        {
                            type.Delete();
                        }
                        else
                        {
                            ViewData["EditError"] = "لا يمكن حذف هذا الطلب يجب ان يكون نوع الطلب طباعة او تحزيم";
                        }
                        
                    }
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            var model = new BusinessLogicLayer.Components.PPM.BookPrintingOperationLogic().GetAll();
            return PartialView("_BookPrintingOperationGridViewPartial", model);
        }
        #endregion

        #region Custom Grid View Button Events
        
        public ActionResult PackExam(int ID)
        {
            string url = string.Format("{0}/Index/{1}", Url.Action("Index", "BookPackingOperation"), ID);
            var model = new BusinessLogicLayer.Entity.PPM.BookPrintingOperation(ID);
            if (model == null)
                return View();
            else
                return Redirect(url);
        }
        #endregion

        BusinessLogicLayer.Components.PPM.BookRepackPackageItemLogic repackItemLogic = new BusinessLogicLayer.Components.PPM.BookRepackPackageItemLogic();

QiyasPlatform/Qiyas.WebAdmin/Views/BookPrintingOperation/Index.cshtml
@model Qiyas.BusinessLogicLayer.Entity.PPM.BookPrintingOperation

@{
    ViewBag.Title = Resources.MainResource.BookPrintingOperationTitle;
}

<div class="page-title">
    <h1>
        @Resources.MainResource.BookPrintingOperationTitle
    </h1>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="widget-container fluid-height clearfix">
            <div class="widget-content padded clearfix">
                @Html.Action("BookPrintingOperationGridViewPartial")


            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="repackModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">اعادة التحزيم</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="RepackId" />
                <div class="form-group">
                    @Html.LabelFor(m => m.RepackFrom, new { @class = "col-md-5  pull-right control-label" })
                    <div class="col-md-7  pull-right">
                        @Html.DropDownListFor(m => m.RepackFrom, new SelectList(new Qiyas.BusinessLogicLayer.Components.PPM.PackagingTypeLogic().GetAll(), "PackagingTypeID", "Name"), new { @class = "form-control col-md-6" })
                        @*@Html.Action("PackagingTypeFromComboBoxPartial")*@

                    </div>
                </div>
                <br />
                <div class="form-group">
                    @Html.LabelFor(m => m.RepackTo, new { @class = "col-md-5  pull-right control-label" })
                    <div class="col-md-7  pull-right">
                        @Html.DropDownListFor(m => m.RepackTo, new SelectList(new Qiyas.BusinessLogicLayer.Components.PPM.PackagingTypeLogic().GetAll(), "PackagingTypeID", "Name"), new { @class = "form-control col-md-6" })
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="RepackButtonSave" onclick="RepackGroup();" class="btn btn-primary">حفظ</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">اغلاق</button>

            </div>
        </div>
    </div>
</div>



@section Scripts {
    <script type="text/javascript">
        function RepackItems() {
            alert('saved');
        }
        function PackagingTypeCombo_BeginCallback(s, e) {
            e.customArgs['StateProvinceID'] = grid.GetEditor('StateProvinceID').GetValue();
        }

        function GetRepackFromDropDownItems() {
            var urlLink = "@Url.Action("GetPackagingTypeFrom", "BookPrintingOperation")";

            $.ajax({
                type: "POST",
                dataType: "json",
                data:  {
                    item: $('#RepackId').val()
                },
                url: urlLink,
                success: function (data) {
                    $("#RepackFrom").children().remove();
                    
                    $.each(data, function (key, value) {
                        $('#RepackFrom')
                         .append($("<option></option>")
                         .attr("value", value.PackagingTypeID)
                         .text(value.PackagingTypeName));
                    });
                },
                error: function (data) {
                    
                }
            });
        }
        function CustomButtonClick(s, e, url) {
            var key = s.GetRowKey(e.visibleIndex);

            if (e.buttonID === "btnPacking") {
                var destUrl = url + "/" + key;
                window.location.href = destUrl;
            }
            else if (e.buttonID === "btnRepack") {
                s.GetRowValues(e.visibleIndex, 'OperationStatusID', OnGetRowValues);
                $('#RepackId').val(key);

            }
        }

        function OnGetRowValues(Value) {
            if (Value == 5 || Value == 7) {
                GetRepackFromDropDownItems();
                $('#repackModal').modal('show');
            }
            else {
                alert('لا يمكن اعادة تحزيم هذا الطلب يجب ان تكون الحزم بالمستودع');
            }
        }

        function RepackGroup() {
            var destUrl = "/BookPackItemRePack/RepackGroup/?bookPrintingId=" + $('#RepackId').val() + "&repackFrom=" + $('#RepackFrom').val() + "&repackTo=" + $('#RepackTo').val();

            window.location.href = destUrl;
        }

    </script>
}

QiyasPlatform/Qiyas.WebAdmin/Views/BookPrintingOperation/_BookPrintingOperationGridViewPartial.cshtml
@{
	var grid = Html.DevExpress().GridView(settings => {
        settings.Name = "BookPrintingOperationGridView";
        settings.CallbackRouteValues = new { Controller = "BookPrintingOperation", Action = "BookPrintingOperationGridViewPartial" };

	    settings.SettingsEditing.AddNewRowRouteValues = new { Controller = "BookPrintingOperation", Action = "BookPrintingOperationGridViewPartialAddNew" };
        settings.SettingsEditing.UpdateRowRouteValues = new { Controller = "BookPrintingOperation", Action = "BookPrintingOperationGridViewPartialUpdate" };
        settings.SettingsEditing.DeleteRowRouteValues = new { Controller = "BookPrintingOperation", Action = "BookPrintingOperationGridViewPartialDelete" };
        settings.KeyFieldName = "BookPrintingOperationID";

        settings.SettingsBehavior.ConfirmDelete = true;
        settings.SettingsEditing.Mode = GridViewEditingMode.PopupEditForm;


        settings.CommandColumn.ShowNewButtonInHeader = true;
        settings.SettingsCommandButton.NewButton.Text = @Resources.MainResource.New;
        settings.SettingsCommandButton.EditButton.Text = " ";
        settings.SettingsCommandButton.EditButton.Styles.Style.CssClass = "fa fa fa-pencil";
        settings.SettingsCommandButton.DeleteButton.Text = " ";
        settings.SettingsCommandButton.DeleteButton.Styles.Style.CssClass = "fa fa-trash-o";
        
        settings.SettingsCommandButton.CancelButton.Text = @Resources.MainResource.Cancel;
        settings.SettingsCommandButton.ClearFilterButton.Text = @Resources.MainResource.Clear;
        settings.SettingsCommandButton.UpdateButton.Text = @Resources.MainResource.Save;
        settings.SettingsCommandButton.UpdateButton.ButtonType = GridViewCommandButtonType.Button;
        settings.SettingsCommandButton.CancelButton.ButtonType = GridViewCommandButtonType.Button;
        settings.CommandColumn.Width = new System.Web.UI.WebControls.Unit("60px");
        settings.CommandColumn.Visible = true;
        settings.CommandColumn.ShowNewButton = false;
        settings.CommandColumn.ShowDeleteButton = true;
        settings.CommandColumn.ShowEditButton = true;
        settings.CommandColumn.CustomButtons.Add(new GridViewCommandColumnCustomButton() { ID = "btnPacking", Text = Resources.MainResource.PackCustomButton });
        settings.CommandColumn.CustomButtons.Add(new GridViewCommandColumnCustomButton() { ID = "btnRepack", Text = Resources.MainResource.Repack });
        settings.ClientSideEvents.CustomButtonClick =
        string.Format("function(s, e) {{ CustomButtonClick(s, e, '{0}'); }}", Url.Action("PackExam", "BookPrintingOperation"));
        
        settings.SettingsSearchPanel.Visible = true;
        settings.SettingsSearchPanel.ShowClearButton = true;
        settings.Styles.SearchPanel.CssClass = "dxgvSearchPanel_MetropolisBlue search_devexpress";

        settings.SettingsText.CommandClearSearchPanelFilter = @Resources.MainResource.Clear;
        settings.SettingsText.SearchPanelEditorNullText = @Resources.MainResource.SearchNullText;
        settings.SettingsText.PopupEditFormCaption = @Resources.MainResource.BookPrintingOperationEditFormTitle;
        settings.SettingsText.ConfirmDelete = @Resources.MainResource.DeleteMessage;
        settings.SettingsText.EmptyDataRow = @Resources.MainResource.NoData;
        settings.SettingsPager.Summary.Text = Resources.MainResource.PageSummaryText;

        settings.SettingsPopup.EditForm.Width = new System.Web.UI.WebControls.Unit("350px");
        settings.SettingsPopup.EditForm.Modal = true;
        settings.SettingsPopup.EditForm.CloseOnEscape = AutoBoolean.True;
        settings.SettingsPopup.EditForm.HorizontalAlign = PopupHorizontalAlign.WindowCenter;
        settings.SettingsPopup.EditForm.VerticalAlign = PopupVerticalAlign.WindowCenter;

        settings.Width = new System.Web.UI.WebControls.Unit("100%");
        settings.RightToLeft = DefaultBoolean.True;
        settings.SettingsPager.Visible = true;
        settings.Settings.ShowFilterRow = true;
        settings.SettingsBehavior.AllowSelectByRowClick = true;
        settings.Styles.AlternatingRow.BackColor = System.Drawing.Color.FromName("#f9f9f9");

				//settings.Columns.Add("Name");
                settings.Columns.Add(col =>
                {
                    col.VisibleIndex = 0;
                    col.UnboundType = DevExpress.Data.UnboundColumnType.Integer;
                    col.FieldName = "RowNumber";
                    col.Caption = "#";
                    col.Width = new System.Web.UI.WebControls.Unit("50px");
                    col.EditFormSettings.Visible = DefaultBoolean.False;
                    col.SortOrder = DevExpress.Data.ColumnSortOrder.Descending;

                });
                settings.CustomColumnDisplayText = (s, e) =>
                {
                    var gr = s as MVCxGridView;
                    if (e.Column.FieldName != "RowNumber")
                        return;
                    e.Value = e.VisibleRowIndex + 1;
                    e.DisplayText = (e.VisibleRowIndex + 1).ToString();
                };
                settings.Columns.Add(column =>
                {
                    column.FieldName = "ExamID";
                    column.EditFormSettings.ColumnSpan = 2;
                    column.Caption = @Resources.ModelResource.ExamCode;
                    column.VisibleIndex = 1;
                    column.Width = new System.Web.UI.WebControls.Unit("20%");
                    column.CellStyle.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Right;
                    column.ColumnType = MVCxGridViewColumnType.ComboBox;
                    var comboProperties = column.PropertiesEdit as ComboBoxProperties;
                    comboProperties.DataSource = (new Qiyas.BusinessLogicLayer.Components.PPM.ExamLogic().GetAllActive());
                    comboProperties.TextField = "ExamCode";
                    comboProperties.ValueField = "ExamID";
                    comboProperties.ValueType = typeof(int);
                    comboProperties.ValidationSettings.RequiredField.IsRequired = true;
                    comboProperties.ValidationSettings.RequiredField.ErrorText = "*";
                    comboProperties.ValidationSettings.Display = Display.Dynamic;
                    comboProperties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.Text;
                });
				
                settings.Columns.Add(column =>
                {
                    column.FieldName = "PrintsForOneModel";
                    column.EditFormSettings.ColumnSpan = 2;
                    column.VisibleIndex = 2;
                    
                    column.Caption = @Resources.ModelResource.PrintsForOneModel;
                    column.Name = "PrintsForOneModel";

                    column.Width = new System.Web.UI.WebControls.Unit("60px");
                    column.ColumnType = MVCxGridViewColumnType.SpinEdit;
                    var textProperties = column.PropertiesEdit as SpinEditProperties;
                    textProperties.ValidationSettings.RequiredField.IsRequired = true;
                    textProperties.ValidationSettings.RequiredField.ErrorText = "*";
                    textProperties.ValidationSettings.Display = Display.Dynamic;
                    textProperties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.Text;
                    //textProperties.Width = new System.Web.UI.WebControls.Unit("100px");
                    textProperties.NumberType = SpinEditNumberType.Integer;
                });
				
                settings.Columns.Add(column =>
                {
                    column.FieldName = "ExamsNeededForA3";
                    column.EditFormSettings.ColumnSpan = 2;
                    column.VisibleIndex = 3;
                    
                    column.Caption = @Resources.ModelResource.ExamsNeededForA3;
                    column.Name = "ExamsNeededForA3";

                    column.Width = new System.Web.UI.WebControls.Unit("60px");
                    column.ColumnType = MVCxGridViewColumnType.SpinEdit;
                    var textProperties = column.PropertiesEdit as SpinEditProperties;
                    textProperties.ValidationSettings.RequiredField.IsRequired = true;
                    textProperties.ValidationSettings.RequiredField.ErrorText = "*";
                    textProperties.ValidationSettings.Display = Display.Dynamic;
                    textProperties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.Text;
                    //textProperties.Width = new System.Web.UI.WebControls.Unit("100px");
                    textProperties.NumberType = SpinEditNumberType.Integer;
                });
				//settings.Columns.Add("ExamsNeededForA4");
				//settings.Columns.Add("");
                settings.Columns.Add(column =>
                {
                    column.FieldName = "ExamsNeededForCD";
                    column.EditFormSettings.ColumnSpan = 2;
                    column.VisibleIndex = 4;
                    
                    column.Caption = @Resources.ModelResource.ExamsNeededForCD;
                    column.Name = "ExamsNeededForCD";

                    column.Width = new System.Web.UI.WebControls.Unit("60px");
                    column.ColumnType = MVCxGridViewColumnType.SpinEdit;
                    var textProperties = column.PropertiesEdit as SpinEditProperties;
                    textProperties.ValidationSettings.RequiredField.IsRequired = true;
                    textProperties.ValidationSettings.RequiredField.ErrorText = "*";
                    textProperties.ValidationSettings.Display = Display.Dynamic;
                    textProperties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.Text;
                    //textProperties.Width = new System.Web.UI.WebControls.Unit("100px");
                    textProperties.NumberType = SpinEditNumberType.Integer;
                });
				
                settings.Columns.Add(column =>
                {
                    column.FieldName = "OperationStatusID";
                    column.EditFormSettings.ColumnSpan = 2;
                    column.VisibleIndex = 5;
                    column.EditFormSettings.Visible = DefaultBoolean.False;
                    column.Caption = @Resources.ModelResource.OperationStatusName;
                    column.Width = new System.Web.UI.WebControls.Unit("20%");
                    column.CellStyle.HorizontalAlign = System.Web.UI.WebControls.HorizontalAlign.Right;
                    column.ColumnType = MVCxGridViewColumnType.ComboBox;
                    var comboProperties = column.PropertiesEdit as ComboBoxProperties;
                    comboProperties.DataSource = (new Qiyas.BusinessLogicLayer.Components.PPM.OperationStatuLogic().GetAll());
                    comboProperties.TextField = "Name";
                    comboProperties.ValueField = "OperationStatusID";
                    comboProperties.ValueType = typeof(int);
                    comboProperties.ValidationSettings.RequiredField.IsRequired = true;
                    comboProperties.ValidationSettings.RequiredField.ErrorText = "*";
                    comboProperties.ValidationSettings.Display = Display.Dynamic;
                    comboProperties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.Text;
                });
			});
		if (ViewData["EditError"] != null){
        grid.SetEditErrorText((string)ViewData["EditError"]);
    }
}
@grid.Bind(Model).GetHtml()