QiyasPlatform/Qiyas.WebAdmin/Controllers/PackageWeightController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DevExpress.Web.Mvc;

namespace Qiyas.WebAdmin.Controllers
{
    [Authorize]
    public class PackageWeightController : Controller
    {
        // GET: PackageWeight
        public ActionResult Index()
        {
            ViewBag.HasError = false;
            ViewBag.NotifyMessage = "";
            return View();
        }

        [ValidateInput(false)]
        public ActionResult PackageWeightGridViewPartial()
        {
            var model = new BusinessLogicLayer.Components.PPM.PackageWeightLogic().GetAllView();
            return PartialView("_PackageWeightGridViewPartial", model);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult PackageWeightGridViewPartialAddNew([ModelBinder(typeof(DevExpressEditorsBinder))] Qiyas.BusinessLogicLayer.Entity.PPM.PackageWeight item)
        {
            
            if (ModelState.IsValid)
            {
                try
                {
                    BusinessLogicLayer.Entity.PPM.PackageWeight package = new BusinessLogicLayer.Entity.PPM.PackageWeight();
                    package.CreatedDate = DateTime.Now;
                    package.ModifiedDate = DateTime.Now;
                    package.Name = item.Name;
                    package.Weight = item.Weight;
                    package.PackageCode = item.PackageCode;
                    package.Save();
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
                ViewData["EditError"] = Resources.MainResource.PleaseCorrectErrors;

            var model = new BusinessLogicLayer.Components.PPM.PackageWeightLogic().GetAllView();
            return PartialView("_PackageWeightGridViewPartial", model);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult PackageWeightGridViewPartialUpdate([ModelBinder(typeof(DevExpressEditorsBinder))] Qiyas.BusinessLogicLayer.Entity.PPM.PackageWeight item)
        {
            
            if (ModelState.IsValid)
            {
                try
                {
                    BusinessLogicLayer.Entity.PPM.PackageWeight package = new BusinessLogicLayer.Entity.PPM.PackageWeight(item.PackageWeightID);
                    package.CreatedDate = DateTime.Now;
                    package.ModifiedDate = DateTime.Now;
                    package.Weight = item.Weight;
                    package.PackageCode = item.PackageCode;
                    package.Name = item.Name;
                    package.Save();
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
                ViewData["EditError"] = Resources.MainResource.PleaseCorrectErrors;
            var model = new BusinessLogicLayer.Components.PPM.PackageWeightLogic().GetAllView();
            return PartialView("_PackageWeightGridViewPartial", model);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult PackageWeightGridViewPartialDelete(System.Int32 PackageWeightID)
        {
            //var model = new object[0];
            if (PackageWeightID >= 0)
            {
                try
                {
                    BusinessLogicLayer.Entity.PPM.PackageWeight package = new BusinessLogicLayer.Entity.PPM.PackageWeight(PackageWeightID);
                    var itemPack = new BusinessLogicLayer.Entity.PPM.BookPackItem(package.PackageCode.Value);
                    if (itemPack.OperationStatusID > 3)
                        ViewData["EditError"] = "لا يمكن حذف هذه الحزمة";
                    else
                    {
                        itemPack.Weight = null;
                        itemPack.OperationStatusID = 2;
                        itemPack.Save();
                        package.Delete();
                    }
                        
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            var model = new BusinessLogicLayer.Components.PPM.PackageWeightLogic().GetAllView();
            return PartialView("_PackageWeightGridViewPartial", model);
        }

        [HttpPost]
        public ActionResult SaveWeight(string item, decimal weight)
        {

            var itemPack = new BusinessLogicLayer.Entity.PPM.BookPackItem(item);
            //if (itemPack.OperationStatusID > 3)
            //    return Json("notsaved");
            if (itemPack.HasObject)
            {
                BusinessLogicLayer.Components.PPM.PackageWeightLogic logic = new BusinessLogicLayer.Components.PPM.PackageWeightLogic();
                var packageOperation = new BusinessLogicLayer.Entity.PPM.BookPackingOperation(itemPack.BookPackingOperationID.Value);
                if(itemPack.OperationStatusID == 2)
                    itemPack.OperationStatusID = 3;
                itemPack.Weight = weight;
                itemPack.Save();
                BusinessLogicLayer.Entity.PPM.PackageWeight package = new BusinessLogicLayer.Entity.PPM.PackageWeight(item);
                if (!package.HasObject)
                {
                    package = new BusinessLogicLayer.Entity.PPM.PackageWeight();
                    package.CreatedDate = DateTime.Now;
                }
                package.ModifiedDate = DateTime.Now;
                package.PackageCode = itemPack.BookPackItemID;
                package.Weight = weight;
                package.Save();
                logic.CheckPackWeightCompleted(packageOperation.BookPrintingOperationID.Value);
                return Json("saved");
            }
            else
            {
                return Json("notsaved");
            }
            
        }

        [HttpPost]
        public ActionResult CheckItem(string item)
        {
            var itemPack = new BusinessLogicLayer.Entity.PPM.BookPackItem(item);
            if (itemPack.HasObject)
            {
                return Json("exists");
            }
            else
            {
                return Json("notexists");
            }
            
            //var model = new BusinessLogicLayer.Entity.PPM.BookPrintingOperation(PrintingOperationID);
            //model.OperationStatusID = 2;
            //model.Save();
            //ViewBag.HasError = false;
            //ViewBag.NotifyMessage = Resources.MainResource.SaveSuccess;
            
        }
    }
}

QiyasPlatform/Qiyas.WebAdmin/Views/PackageWeight/Index.cshtml
@model Qiyas.BusinessLogicLayer.Entity.PPM.PackageWeight

@{
    ViewBag.Title = Resources.MainResource.PackageWeightTitle;
}
<div class="page-title">
    <h1>
        @Resources.MainResource.PackageWeightTitle
    </h1>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="widget-container fluid-height clearfix">
            <div class="widget-content padded clearfix">
                
                @using (Html.BeginForm("SaveWeight", "PackageWeight", FormMethod.Post, new { @class = "form-horizontal", role = "form", @id = "packForm", @name = "packForm" }))
                {
                    @Html.AntiForgeryToken()

                    <div id="errorMessage" class="alert alert-danger" style="display:none;">يوجد خطأ في الحفظ يرجى مراجعة البيانات</div>
                    <div id="successMessage" class="alert alert-success" style="display:none;">تم الحفظ بنجاح</div>
                    <div class="col-lg-4 pull-right">
                        @Html.ValidationSummary("", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(m => m.PackageCode, new { @class = "col-md-5  pull-right control-label" })
                            <div class="col-md-4  pull-right">
                                @Html.TextBoxFor(m => m.PackageCode, new { @class = "form-control" })
                            </div>
                            <div class="error" style="color: forestgreen;display:none;" id="packageExists">حزمة صحيحة</div>
                            <div class="error" style="color: darkred;display:none;" id="packageDoesntExist">لا يمكن تعديل هذه الحزمة</div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.Weight, new { @class = "col-md-5  pull-right control-label" })
                            <div class="col-md-4 pull-right">
                                @Html.TextBoxFor(m => m.Weight, new { @class = "form-control", @type = "number" })
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <div class="col-md-offset-3 col-md-10 ">
                                <input type="button" name="SaveWeight" id="SaveWeight" value="حفظ" class="btn btn-default btn-primary pull-left" />
                            </div>
                        </div>
                        <hr />
                    </div>
                    <br /><br />
                    @Html.Action("PackageWeightGridViewPartial")



                }
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @*@Scripts.Render("~/bundles/jqueryval")*@
    <script type="text/javascript">
        
        $("#SaveWeight").click(function (e) {
            e.preventDefault();
            var urlLink = "@Url.Action("SaveWeight", "PackageWeight")";
            
            $.ajax({
                type: "POST",
                dataType: "json",
                data:  {
                    item: $('#PackageCode').val(),
                    weight: $('#Weight').val()
                },
                url: urlLink,
                success: function (data) {
                    if (data == "saved") {
                        $('#errorMessage').hide();
                        $('#successMessage').fadeIn('slow', function () {
                            $(this).delay(3000).fadeOut('slow');
                        });
                        $('#PackageCode').val('');
                        $('#Weight').val('');
                        $('#packageDoesntExist').hide();
                        $('#packageExists').hide();
                        $("#PackageCode").focus();
                        PackageWeightGridView.PerformCallback();
                    }
                    else {
                        $('#successMessage').hide();
                        $('#errorMessage').fadeIn('slow', function () {
                            $(this).delay(5000).fadeOut('slow');
                        });
                    }

                },
                error: function (data) {
                    $('#successMessage').hide();
                    $('#errorMessage').fadeIn('slow', function () {
                        $(this).delay(5000).fadeOut('slow');
                    });
                }
            });
            return false;
        });
        $("#PackageCode").change(function () {
            var urlLink = "@Url.Action("CheckItem", "PackageWeight")";

            $.ajax({
                type: "POST",
                dataType: "json",
                data:  {
                    item: $('#PackageCode').val()
                },
                url: urlLink,
                success: function (data) {
                    if (data == "exists") {
                        $('#packageDoesntExist').hide();
                        $('#packageExists').show();
                    }
                    else {
                        $('#packageExists').hide();
                        $('#packageDoesntExist').show();
                    }

                },
                error: function (data) {
                    $('#packageExists').hide();
                    $('#packageDoesntExist').show();
                }
            });
        });
        $('#PackageCode').focus();
        $("form").bind("keypress", function (e) {
            if (e.keyCode == 13) {
                if ($('#Weight').val() == '' || $('#Weight').val() == '0')
                    $('#Weight').focus();
                else if ($('#PackageCode').val() != '' && $('#PackageCode').val() != '0') {
                    $("#SaveWeight").trigger('click');
                }
                else {
                    $('#PackageCode').focus();
                }
            }
        });
</script>
    
}

QiyasPlatform/Qiyas.WebAdmin/Views/PackageWeight/_PackageWeightGridViewPartial.cshtml
@{
	var grid = Html.DevExpress().GridView(settings => {
        settings.Name = "PackageWeightGridView";
        settings.CallbackRouteValues = new { Controller = "PackageWeight", Action = "PackageWeightGridViewPartial" };

	    settings.SettingsEditing.AddNewRowRouteValues = new { Controller = "PackageWeight", Action = "PackageWeightGridViewPartialAddNew" };
        settings.SettingsEditing.UpdateRowRouteValues = new { Controller = "PackageWeight", Action = "PackageWeightGridViewPartialUpdate" };
        settings.SettingsEditing.DeleteRowRouteValues = new { Controller = "PackageWeight", Action = "PackageWeightGridViewPartialDelete" };
        settings.KeyFieldName = "PackageWeightID";

        settings.SettingsEditing.Mode = GridViewEditingMode.PopupEditForm;
        settings.SettingsBehavior.ConfirmDelete = true;
        settings.CommandColumn.ShowNewButtonInHeader = true;
        settings.SettingsCommandButton.NewButton.Text = @Resources.MainResource.New;
        settings.SettingsCommandButton.EditButton.Text = " ";
        settings.SettingsCommandButton.EditButton.Styles.Style.CssClass = "fa fa fa-pencil";
        settings.SettingsCommandButton.DeleteButton.Text = " ";
        settings.SettingsCommandButton.DeleteButton.Styles.Style.CssClass = "fa fa-trash-o";
        settings.SettingsCommandButton.CancelButton.Text = @Resources.MainResource.Cancel;
        settings.SettingsCommandButton.ClearFilterButton.Text = @Resources.MainResource.Clear;
        settings.SettingsCommandButton.UpdateButton.Text = @Resources.MainResource.Save;
        settings.SettingsCommandButton.UpdateButton.ButtonType = GridViewCommandButtonType.Button;
        settings.SettingsCommandButton.CancelButton.ButtonType = GridViewCommandButtonType.Button;
        settings.CommandColumn.Width = new System.Web.UI.WebControls.Unit("60px");
        settings.CommandColumn.Visible = true;
        settings.CommandColumn.ShowNewButton = false;
        settings.CommandColumn.ShowDeleteButton = true;
        settings.CommandColumn.ShowEditButton = false;

        settings.SettingsSearchPanel.Visible = true;
        settings.SettingsSearchPanel.ShowClearButton = true;
        settings.Styles.SearchPanel.CssClass = "dxgvSearchPanel_MetropolisBlue search_devexpress";

        settings.SettingsText.CommandClearSearchPanelFilter = @Resources.MainResource.Clear;
        settings.SettingsText.SearchPanelEditorNullText = @Resources.MainResource.SearchNullText;
        settings.SettingsText.PopupEditFormCaption = @Resources.MainResource.PackageWeightEditFormTitle;
        settings.SettingsText.ConfirmDelete = @Resources.MainResource.DeleteMessage;
        settings.SettingsText.EmptyDataRow = @Resources.MainResource.NoData;
        settings.SettingsPager.Summary.Text = Resources.MainResource.PageSummaryText;

        settings.Width = new System.Web.UI.WebControls.Unit("100%");
        settings.RightToLeft = DefaultBoolean.True;
        settings.SettingsPager.Visible = true;
        settings.Settings.ShowFilterRow = false;
        settings.SettingsBehavior.AllowSelectByRowClick = true;
        settings.Styles.AlternatingRow.BackColor = System.Drawing.Color.FromName("#f9f9f9");

        settings.SettingsPopup.EditForm.Width = new System.Web.UI.WebControls.Unit("350px");
        settings.SettingsPopup.EditForm.Modal = true;
        settings.SettingsPopup.EditForm.CloseOnEscape = AutoBoolean.True;
        settings.SettingsPopup.EditForm.HorizontalAlign = PopupHorizontalAlign.WindowCenter;
        settings.SettingsPopup.EditForm.VerticalAlign = PopupVerticalAlign.WindowCenter;


                settings.Columns.Add(col =>
                {
                    col.VisibleIndex = 0;
                    col.UnboundType = DevExpress.Data.UnboundColumnType.Integer;
                    col.FieldName = "RowNumber";
                    col.Caption = "#";
                    col.Width = new System.Web.UI.WebControls.Unit("50px");
                    col.EditFormSettings.Visible = DefaultBoolean.False;

                });
                settings.CustomColumnDisplayText = (s, e) =>
                {
                    var gr = s as MVCxGridView;
                    if (e.Column.FieldName != "RowNumber")
                        return;
                    e.Value = e.VisibleRowIndex + 1;
                    e.DisplayText = (e.VisibleRowIndex + 1).ToString();
                };
                settings.Columns.Add(column =>
                {
                    column.FieldName = "Name";
                    column.EditFormSettings.ColumnSpan = 2;
                    column.Caption = @Resources.ModelResource.PackageWeightName;
                    column.Visible = false;
                    column.ColumnType = MVCxGridViewColumnType.TextBox;
                    var textProperties = column.PropertiesEdit as TextBoxProperties;
                    textProperties.ValidationSettings.RequiredField.IsRequired = true;
                    textProperties.ValidationSettings.RequiredField.ErrorText = "*";
                    textProperties.ValidationSettings.Display = Display.Dynamic;
                    textProperties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.Text;

                });

                settings.Columns.Add(column =>
                {
                    column.FieldName = "PackCode";
                    column.EditFormSettings.ColumnSpan = 2;
                    column.Caption = @Resources.ModelResource.PackageCode;

                    column.ColumnType = MVCxGridViewColumnType.TextBox;
                    var textProperties = column.PropertiesEdit as TextBoxProperties;
                    textProperties.ValidationSettings.RequiredField.IsRequired = true;
                    textProperties.ValidationSettings.RequiredField.ErrorText = "*";
                    textProperties.ValidationSettings.Display = Display.Dynamic;
                    textProperties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.Text;
                    
                });

                settings.Columns.Add(column =>
                {
                    column.FieldName = "Weight";
                    column.EditFormSettings.ColumnSpan = 2;
                    column.Caption = @Resources.ModelResource.Weight;

                    column.ColumnType = MVCxGridViewColumnType.SpinEdit;
                    var textProperties = column.PropertiesEdit as SpinEditProperties;
                    textProperties.ValidationSettings.RequiredField.IsRequired = true;
                    textProperties.ValidationSettings.RequiredField.ErrorText = "*";
                    textProperties.ValidationSettings.Display = Display.Dynamic;
                    textProperties.ValidationSettings.ErrorDisplayMode = ErrorDisplayMode.Text;
                    textProperties.NumberType = SpinEditNumberType.Float;

                });
			});
		if (ViewData["EditError"] != null){
        grid.SetEditErrorText((string)ViewData["EditError"]);
    }
}
@grid.Bind(Model).GetHtml()